version: '3'
services:
  database:
    image: postgres
    ports:
      - '${DB_PORT}:5432'
    environment:
      
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - db-data:/var/lib/postgresql/data


volumes:
  db-data:

